const CONSTANTS = {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_SCORE: 'CHANGE_SCORE',
    CHANGE_LEVEL: 'CHANGE_LEVEL',
    CHANGE_SECTION: 'CHANGE_SECTION',
    CHANGE_PUZZLE: 'CHANGE_PUZZLE',
    CHANGE_DEVICE: 'CHANGE_DEVICE',
    CHANGE_OPENED: 'CHANGE_OPENED'
};

export default CONSTANTS;
