const CONSTANTS = {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_SCORE: 'CHANGE_SCORE',
    CHANGE_LEVEL: 'CHANGE_LEVEL',
    CHANGE_SECTION: 'CHANGE_SECTION',
    CHANGE_PUZZLE: 'CHANGE_PUZZLE'
};

export default CONSTANTS;
