const en = {
    intro: 'home',
    experience: 'experience',
    studies: 'studies',
    projects: 'projects',
    welcome: '¡Bienvenido!',
    computerScience: 'Computer Science',
    frontender: 'Frontend developer',
    fullstack: 'Fullstack developer',
    designPatterns: 'Design patterns',
    edreamsPosition: 'Full Stack Developer',
    edreamsDescription: 'Web development and application maintenance',
    theCocktailPosition: 'Full Stack Developer',
    theCocktailDescription: 'Web development and application maintenance',
    simbiosysPosition: 'Full Stack Developer',
    simbiosysDescription: 'Web development and project management',
    wesoPosition: 'Full Stack Developer',
    wesoDescription: 'Web development and project management',
    espiralPosition: 'Full Stack Developer',
    espiralDescription: 'Web development and product maintenance',
    ingescoPosition: 'Backend Developer',
    ingescoDescription: 'Web development and application maintenance',
    cetsPosition: 'Teacher',
    cetsDescription: 'Private lessons teacher for College students',
    programming: 'Programming Introduction',
    dataStructures: 'Data Structures',
    algorithms: 'Algorithms',
    master: 'Master in Web Engineering',
    compilers: 'Compilers and Interpreters',
    degree: 'Computer Engineering',
    operatingSystems: 'Operating Systems',
    networks: 'Networks',
    dataBases: 'Data Bases',
    softwareEngineering: 'Software Engineering',
    universityOviedo: 'University of Oviedo',
    ireland: 'Ireland',
    spanish: 'Spanish',
    asturian: 'Asturian',
    english: 'English',
    french: 'French',
    german: 'German',
    italian: 'Italian',
    native: 'Native Speaker',
    basicKnowledge: 'Basic Knowledge',
    eoi: 'State Language School',
    title: 'title',
    tasks: 'tasks',
    wwwfTasks:
        'Project responsible. UX integration and WordPress architecture development.',
    a4aiTasks: 'Project responsible. Design, development and deployment.',
    windexTasks: 'Project responsible. Design, development and deployment.',
    circoTasks: 'Project responsible. Design, development and deployment.',
    wescountryTasks: 'Project responsible. Design, development and deployment.',
    landportalTasks: 'Project responsible. Design, development and deployment.',
    wfTasks: 'UX Project responsible. Design, development and deployment.',
    fechu: 'Made in Asturias'
};

export default en;
